kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: opsgenie-1
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
      routes:
        - receiver: opsgenie-1
          match:
            severity: opsgenie-1
          group_wait: 10s
          repeat_interval: 1m
        - receiver: opsgenie-2
          match:
            severity: opsgenie-2
          group_wait: 10s
          repeat_interval: 1m
 
    receivers:
    - name: opsgenie-1
      opsgenie_configs:
      - api_key: <api-key-1>
    - name: opsgenie-2
      opsgenie_configs:
      - api_key: <api-key-2>
